MIN_PROXIMITY = 0.4  # 60% схожести  # чем больше, тем менее похожжие будут попадать в рекомендации
GENDER_PROXIMITY_MEASURE_WEIGHT = 0.5
THEME_PROXIMITY_MEASURE_WEIGHT = 1.4
YEAR_OF_BIRTH_PROXIMITY_MEASURE_WEIGHT = 1.1
MEMBERS_NUM_PROXIMITY_MEASURE_WEIGHT = 0.6
GENRE_PROXIMITY_MEASURE_WEIGHT = 2
