MIN_PROXIMITY = 0.4  # то есть выводит схожих на (1 - MIN_PROXIMITY)%. Чем >, тем < похожие будут попадать в рек-ции
GENDER_PROXIMITY_MEASURE_WEIGHT = 0.5
THEME_PROXIMITY_MEASURE_WEIGHT = 1
YEAR_OF_BIRTH_PROXIMITY_MEASURE_WEIGHT = 1.1
MEMBERS_NUM_PROXIMITY_MEASURE_WEIGHT = 0.6
GENRE_PROXIMITY_MEASURE_WEIGHT = 1
