version: "3"
services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=ru_RU.utf8 --lc-ctype=ru_RU.utf8'
    volumes:
      - hiphop-db-data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  hip-hop-bot-service:
    build: .
    environment:
      MODE: "dev"
      DB_USER: "program"
      DB_PASSWORD: "test"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "hiphop_bot"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  hiphop-db-data: