from hiphop_bot.dialog_bot.models.const import SexFilter
from hiphop_bot.dialog_bot.models.artists_names_aliases import ArtistsNamesAliasesModel

keywords = {
    'search': ('найти', 'похожий', 'схожий',),
    'like/how': ('как', 'каков', 'какой', 'тип'),
    'artist': ('артист', 'исполнитель', 'музыкант', 'рэпер', 'певец'),
    'result': ('результат',),
    'line': ('строка', 'сточка',),
    'restrict': ('ограничить', 'ограничение',),
    'po': ('по',),
    'genre': ('жанр', 'стиль',),
    'tree': ('дерево',),
    'about': ('о', 'про'),
    'except': ('кроме', 'исключая'),
    'recommend': ('посоветовать', 'порекомендовать', 'рекомендация', 'подобрать'),
    'show': ('показывать', 'показать', 'выводить', 'вывести', 'прислать'),
    'include': ('оставить', 'оставлять', 'добавить', 'включить', 'прибавить', 'выбрать', 'вернуть'),
    'exclude': (
        'убрать', 'исключать', 'исключить', 'отмести', 'отметать', 'выкинуть', 'выкидывать', 'отсеить', 'отсеивать',
        'удалять', 'удалить', 'удаль', 'отфильтровать', 'сбросить',
    ),
    'all': ('весь', 'всё'),
    'year': ('год',),
    'older': ('старший', 'большой', 'за', 'от', 'взрослый'),
    'younger': ('младший', 'маленький', 'до', 'молодой'),
    'range': ('между', 'диапазон',),
    'solo': ('соло', 'сольные', 'сольный',),
    'duet': ('дуэт', 'дуэты', 'дуэтов',),
    'group': ('группа', 'группы', 'групп',),
    'age': ('возраст',),

    'talk about': ('рассказать',),
    'info': ('информация', 'узнать'),

    'like': ('нравиться', 'лайк', 'любить', 'любимый', 'лайковый', 'понравиться', 'интерес', 'интересно', 'лайкам'),

    'dislike': ('не нравиться', 'дизлайк', 'не любить', 'нелюбимый', 'дизлайковый',),

    'to me': ('я', 'мой'),

    'how many': ('сколько',),
    'number': ('количество',),

    'restart': ('вернуться', 'начало', 'новый', 'начать', 'заново', 'сначала'),

    'filter': ('фильтр',),

    'you': ('ты', 'свой', 'твой'),
    'who': ('кто', 'что',),
    'opportunities': ('функция', 'функционал', 'возможность', 'мочь', 'уметь'),
    'algorithm': ('алгоритм', 'работать', 'устройство', 'устроенный'),
}

for tag1, aliases1 in keywords.items():
    for tag2, aliases2 in keywords.items():
        if tag1 != tag2:
            if set(aliases1) & set(aliases2):
                print(tag1, tag2, set(aliases1) & set(aliases2))

GENDERS = {
    'мужcкой': SexFilter.MALE,
    'мужского': SexFilter.MALE,
    'мужчин': SexFilter.MALE,
    'мужчина': SexFilter.MALE,
    'мальчиков': SexFilter.MALE,
    'мальчик': SexFilter.MALE,
    'парень': SexFilter.MALE,
    'парней': SexFilter.MALE,
    'женский': SexFilter.FEMALE,
    'женского': SexFilter.FEMALE,
    'женщин': SexFilter.FEMALE,
    'женщина': SexFilter.FEMALE,
    'девушка': SexFilter.FEMALE,
    'девушек': SexFilter.FEMALE,
    'девочек': SexFilter.FEMALE,
    'девочка': SexFilter.FEMALE,

}


def load_artists_aliases() -> dict | None:
    artists_names_aliases_model = ArtistsNamesAliasesModel()
    all_artists_names_aliases = artists_names_aliases_model.get_all()
    artists = {}
    for artist_aliases in all_artists_names_aliases:
        artist_name = artist_aliases.artist_name
        aliases = artist_aliases.aliases
        artists.update({alias: artist_name for alias in aliases})
    return artists


GENRES = {
    'newschool': 'newschool',
    'new school': 'newschool',
    'ньюскул': 'newschool',
    'ньюскула': 'newschool',
    'нью скул': 'newschool',
    'нью скула': 'newschool',
    'новая школа': 'newschool',
    'новой школы': 'newschool',
    'alternative': 'alternative',
    'альтернатива': 'alternative',
    'альтернативы': 'alternative',
    'oldschool': 'oldschool',
    'олдскул': 'oldschool',
    'олдскула': 'oldschool',
    'олд скул': 'oldschool',
    'олд скула': 'oldschool',
    'старая школа': 'oldschool',
    'старой школы': 'oldschool',
    'emo': 'emo',
    'эмо': 'emo',
    'raprock': 'raprock',
    'rap rock': 'raprock',
    'рэп рок': 'raprock',
    'рэп-рок': 'raprock',
    'реп рок': 'raprock',
    'реп-рок': 'raprock',
    'рэп рока': 'raprock',
    'рэп-рока': 'raprock',
    'реп рока': 'raprock',
    'реп-рока': 'raprock',
    'cloud': 'cloud',
    'клауд': 'cloud',
    'клауда': 'cloud',
    'club': 'club',
    'клуб': 'club',
    'клуба': 'club',
    'клубный': 'club',
    'drill': 'drill',
    'дрилл': 'drill',
    'дрилла': 'drill',
    'grime': 'grime',
    'грайм': 'grime',
    'грайма': 'grime',
    'mumble': 'mumble',
    'мамбл': 'mumble',
    'мамбла': 'mumble',
    'phonk': 'phonk',
    'фонк': 'phonk',
    'фонка': 'phonk',
    'hardcore': 'hardcore',
    'хардкор': 'hardcore',
    'хардкора': 'hardcore',
    'horrorcore': 'horrorcore',
    'хорроркор': 'horrorcore',
    'хорроркора': 'horrorcore',
    'хороркор': 'horrorcore',
    'хороркора': 'horrorcore',
    'rapcore': 'rapcore',
    'рэпкор': 'rapcore',
    'рэпкора': 'rapcore',
    'репкор': 'rapcore',
    'репкора': 'rapcore',
    'реп кор': 'rapcore',
    'реп кора': 'rapcore',
    'рэп кор': 'rapcore',
    'рэп кора': 'rapcore',
    'реп-кор': 'rapcore',
    'реп-кора': 'rapcore',
    'рэп-кор': 'rapcore',
    'рэп-кора': 'rapcore',
    'underground': 'underground',
    'андеграунд': 'underground',
    'андеграунда': 'underground',
    'hookah': 'hookah',
    'кальян': 'hookah',
    'кальяна': 'hookah',
    'кальянный': 'hookah',
    'кальянного': 'hookah',
    'pop': 'popular',
    'поп': 'popular',
    'попа': 'popular',
    'поп-рэп': 'popular',
    'поп-реп': 'popular',
    'поп рэп': 'popular',
    'поп реп': 'popular',
    'gangsta': 'gangsta',
    'гангста': 'gangsta',
    'ганста': 'gangsta',
    'workout': 'workout',
    'воркаут': 'workout',
    'воркаута': 'workout',
    'спортивный': 'workout',
    'спортивном': 'workout',
    'спортивного': 'workout',
    'спорт': 'workout',
    'спорта': 'workout',
    'electronichiphop': 'electronichiphop',
    'электронный': 'electronichiphop',
    'электронника': 'electronichiphop',
    'электро': 'electronichiphop',
    'электроникхипхоп': 'electronichiphop',
    'электроникхип-хоп': 'electronichiphop',
    'электроник хип-хоп': 'electronichiphop',
    'электроник-хип-хоп': 'electronichiphop',
    'эллектронный хип-хоп': 'electronichiphop',
    'эллектронный хипхоп': 'electronichiphop',
    'эллектронного хипхопа': 'electronichiphop',
    'олдскулхардкор': 'oldschoolhardcore',
    'олдскул хардкор': 'oldschoolhardcore',
    'олдскул-хардкор': 'oldschoolhardcore',
    'олдскулхардкора': 'oldschoolhardcore',
    'олдскул хардкора': 'oldschoolhardcore',
    'олдскул-хардкора': 'oldschoolhardcore',
    'олд скулхардкор': 'oldschoolhardcore',
    'олд скул хардкор': 'oldschoolhardcore',
    'олд скул-хардкор': 'oldschoolhardcore',
    'олд скулхардкора': 'oldschoolhardcore',
    'олд скул хардкора': 'oldschoolhardcore',
    'олд скул-хардкора': 'oldschoolhardcore',
    'русский рэп': 'russianrap',
    'русского рэпа': 'russianrap',
    'русский реп': 'russianrap',
    'русского репа': 'russianrap',
}